### ISSUE TITLE
@skip is broken

### ISSUE THREAD

**Issue by rdickert** [stewartml/stucumber#4]
`@skip` used to work in 0.10.0. Now it throws an error that appears to point to [this line of code](https://github.com/stewartml/stucumber/blob/master/src/lib/generic-transformer.ts#L123):

```
    TypeError: Cannot read property 'length' of undefined

      at attributes.find (node_modules/stucumber/src/lib/generic-transformer.ts:123:74)
      at Array.find (native)
      at GenericTransformer.applyAttributes (node_modules/stucumber/src/lib/generic-transformer.ts:123:20)
      at GenericTransformer.transformScenario (node_modules/stucumber/src/lib/generic-transformer.ts:89:12)
      at transformFile.transformFeature.feature.scenarios.map (node_modules/stucumber/src/lib/transformer.ts:52:16)
          at Array.map (<anonymous>)
      at GenericTransformer.transform (node_modules/stucumber/src/lib/transformer.ts:51:27)
      at Object.process (node_modules/gherkin-jest/src/lib/process.ts:26:22)
```

I get this error if I add `@skip` to any feature or scenario.

**Comment by stewartml** [comment]
Thanks for reporting.

Fixed [here](https://github.com/stewartml/stucumber/commit/632afce6f548d7d0ea168c981811a062f9582096#diff-7b43b007342dd40b6b4a56010ea03084R35)

Tested [here](https://github.com/stewartml/stucumber/blob/cb1badb5d3e9ab0ab9d0dcf5724667affe316f64/src/test/integration.feature#L13).

**Comment by rdickert** [comment]
awesome, thanks @stewartml!
